import { Poppins, Barlow } from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";

const fontDisplay = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-display",
});

const fontBody = Barlow({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-body",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-[#FAFBFC] antialiased",
          fontBody.variable,
          fontDisplay.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
